# Dataset View

In [17]:
import pandas as pd

calendar_df = pd.read_csv("../data/raw/calendar.csv")
sales_evaluation_df = pd.read_csv("../data/raw/sales_train_evaluation.csv")
sales_validation_df = pd.read_csv("../data/raw/sales_train_validation.csv")
sell_prices_df = pd.read_csv("../data/raw/sell_prices.csv")

In [18]:
calendar_df.sample(5)

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
439,2012-04-12,11211,Thursday,6,4,2012,d_440,NaN,NaN,NaN,NaN,0,1,1
1005,2013-10-30,11340,Wednesday,5,10,2013,d_1006,NaN,NaN,NaN,NaN,0,0,0
1856,2016-02-28,11605,Sunday,2,2,2016,d_1857,NaN,NaN,NaN,NaN,0,0,0
815,2013-04-23,11313,Tuesday,4,4,2013,d_816,NaN,NaN,NaN,NaN,0,0,0
1056,2013-12-20,11347,Friday,7,12,2013,d_1057,NaN,NaN,NaN,NaN,0,0,0

In [19]:
sales_evaluation_df.sample(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
21109,FOODS_3_591_TX_3_evaluation,FOODS_3_591,FOODS_3,FOODS,TX_3,TX,5,2,0,8,...,0,0,0,0,1,0,0,0,0,2
4066,HOUSEHOLD_1_462_CA_2_evaluation,HOUSEHOLD_1_462,HOUSEHOLD_1,HOUSEHOLD,CA_2,CA,0,5,2,7,...,0,0,0,0,2,11,0,10,2,8
3618,HOUSEHOLD_1_005_CA_2_evaluation,HOUSEHOLD_1_005,HOUSEHOLD_1,HOUSEHOLD,CA_2,CA,2,3,0,1,...,3,6,6,5,0,2,5,6,5,4
27065,FOODS_3_449_WI_2_evaluation,FOODS_3_449,FOODS_3,FOODS,WI_2,WI,10,2,7,10,...,1,2,3,6,4,2,1,2,0,2
20970,FOODS_3_452_TX_3_evaluation,FOODS_3_452,FOODS_3,FOODS,TX_3,TX,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [20]:
sales_validation_df.sample(5)

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
8948,FOODS_3_626_CA_3_validation,FOODS_3_626,FOODS_3,FOODS,CA_3,CA,0,0,0,0,...,1,2,1,0,0,0,1,1,1,1
28509,HOUSEHOLD_1_513_WI_3_validation,HOUSEHOLD_1_513,HOUSEHOLD_1,HOUSEHOLD,WI_3,WI,0,0,0,0,...,0,2,2,1,1,1,0,1,0,3
29954,FOODS_3_289_WI_3_validation,FOODS_3_289,FOODS_3,FOODS,WI_3,WI,0,1,0,1,...,0,0,0,0,1,0,0,0,1,1
19005,HOUSEHOLD_1_151_TX_3_validation,HOUSEHOLD_1_151,HOUSEHOLD_1,HOUSEHOLD,TX_3,TX,0,0,0,0,...,5,2,5,1,8,8,7,5,0,0
15320,HOBBIES_1_078_TX_2_validation,HOBBIES_1_078,HOBBIES_1,HOBBIES,TX_2,TX,4,0,0,0,...,0,2,5,0,0,1,0,1,0,1

In [21]:
sell_prices_df.sample(5)

        store_id          item_id  wm_yr_wk  sell_price
3551899     TX_2  HOUSEHOLD_1_064     11325        5.78
2070081     CA_4    HOBBIES_1_189     11232        0.46
5030292     WI_1  HOUSEHOLD_1_468     11310        4.98
814813      CA_2    HOBBIES_2_092     11349        4.97
2220035     CA_4  HOUSEHOLD_1_326     11148        4.88

## reshaping the sales train datasets

In [23]:
def transform_sales_data(sales_df: pd.DataFrame) -> pd.DataFrame:
    # Product and location columns to keep
    id_columns = [
        "item_id",
        "dept_id",
        "cat_id",
        "store_id",
        "state_id",
    ]

    # Select only columns such as d_1, d_2, d_3, ...
    day_columns = [
        column
        for column in sales_df.columns
        if column.startswith("d_")
    ]

    long_df = sales_df.melt(
        id_vars=id_columns,
        value_vars=day_columns,
        var_name="d",
        value_name="sales",
    )

    return long_df

In [26]:
new_sales_validation_df = transform_sales_data(sales_validation_df)
new_sales_validation_df.sample(5)

,item_id,dept_id,cat_id,store_id,state_id,d,sales
414233,FOODS_3_394,FOODS_3,FOODS,TX_2,TX,d_14,0
16173553,FOODS_1_047,FOODS_1,FOODS,TX_1,TX,d_531,0
5955585,HOUSEHOLD_1_330,HOUSEHOLD_1,HOUSEHOLD,CA_4,CA,d_196,0
10199248,HOBBIES_1_352,HOBBIES_1,HOBBIES,TX_2,TX,d_335,0
40982167,HOBBIES_2_143,HOBBIES_2,HOBBIES,CA_2,CA,d_1345,0

In [27]:
new_sales_evaluation_df = transform_sales_data(sales_evaluation_df)
new_sales_evaluation_df.sample(5)

,item_id,dept_id,cat_id,store_id,state_id,d,sales
33466975,HOUSEHOLD_2_055,HOUSEHOLD_2,HOUSEHOLD,TX_3,TX,d_1098,0
42881041,FOODS_3_732,FOODS_3,FOODS,CA_4,CA,d_1407,1
2929134,FOODS_2_268,FOODS_2,FOODS,CA_1,CA,d_97,0
6607875,HOUSEHOLD_1_132,HOUSEHOLD_1,HOUSEHOLD,WI_1,WI,d_217,0
53365804,FOODS_2_380,FOODS_2,FOODS,CA_3,CA,d_1751,7

## combine date to the new dataframe

In [43]:
def add_calendar_info(sales_df: pd.DataFrame, calendar_df: pd.DataFrame) -> pd.DataFrame:

    result_df = sales_df.merge(
        calendar_df[["d", "date", "wm_yr_wk"]],
        on="d",
        how="left"
    )
    result_df["date"] = pd.to_datetime(result_df["date"])

    return result_df

In [46]:
new_sales_validation_df = add_calendar_info(new_sales_validation_df, calendar_df)
new_sales_evaluation_df = add_calendar_info(new_sales_evaluation_df, calendar_df)

## combine sales with new dataframe

In [48]:
def add_sales_info(sales_df: pd.DataFrame, sell_prices_df: pd.DataFrame) -> pd.DataFrame:

    result_df = sales_df.merge(
        sell_prices_df,
        on=["store_id", "item_id", "wm_yr_wk"],
        how="left"
    )

    return result_df

In [50]:
new_sales_validation_df = add_sales_info(new_sales_validation_df, sell_prices_df)
new_sales_evaluation_df = add_sales_info(new_sales_evaluation_df, sell_prices_df)

In [51]:
new_sales_validation_df.sample(5)

,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,sell_price
23685894,HOUSEHOLD_2_166,HOUSEHOLD_2,HOUSEHOLD,WI_2,WI,d_777,0,2013-03-15,11307,8.67
56505645,HOUSEHOLD_2_482,HOUSEHOLD_2,HOUSEHOLD,CA_3,CA,d_1854,0,2016-02-25,11604,5.73
8238019,FOODS_3_446,FOODS_3,FOODS,CA_2,CA,d_271,17,2011-10-26,11139,1.18
46966331,FOODS_3_360,FOODS_3,FOODS,CA_4,CA,d_1541,0,2015-04-18,11512,1.98
49610576,HOBBIES_1_306,HOBBIES_1,HOBBIES,CA_2,CA,d_1628,0,2015-07-14,11524,13.98

In [52]:
new_sales_evaluation_df.sample(5)

,item_id,dept_id,cat_id,store_id,state_id,d,sales,date,wm_yr_wk,sell_price
56312829,HOUSEHOLD_1_290,HOUSEHOLD_1,HOUSEHOLD,WI_3,WI,d_1847,2,2016-02-18,11603,9.84
41357718,HOUSEHOLD_1_527,HOUSEHOLD_1,HOUSEHOLD,TX_1,TX,d_1357,3,2014-10-16,11437,5.24
31959135,FOODS_3_342,FOODS_3,FOODS,CA_2,CA,d_1049,0,2013-12-12,11346,1.00
8347065,FOODS_2_126,FOODS_2,FOODS,WI_1,WI,d_274,0,2011-10-29,11140,NaN
6789787,FOODS_3_489,FOODS_3,FOODS,TX_3,TX,d_223,0,2011-09-08,11132,NaN

# Save Silver Dataset as a CSV

In [54]:
import pathlib


SILVER_DATA_DIR = pathlib.Path("../data/silver")
SILVER_DATA_DIR.mkdir(parents=True, exist_ok=True)


new_sales_evaluation_df.to_csv(SILVER_DATA_DIR / "new_sales_evaluation.csv", index=False)
new_sales_validation_df.to_csv(SILVER_DATA_DIR / "new_sales_validation.csv", index=False)

---
 Create Golden Dataset
---